In [2]:
import pandas as pd
xl = pd.ExcelFile("/home/grenzz/funnnn/Mess-Meal-Forecasting/data/raw/meal wise head count (2024 - 2025 - 2026(may)).xlsx")
print(xl.sheet_names)

['Sheet1', 'Sheet2', 'Sheet3', 'Sheet4', 'Sheet5', 'Sheet6', 'Sheet7', 'Sheet8', 'Sheet9', 'Sheet10', 'Sheet11', 'Sheet12', 'Sheet13', 'Sheet14', 'Sheet15', 'Sheet16', 'Sheet17', 'Sheet18', 'Sheet19', 'Sheet20', 'Sheet21', 'Sheet22', 'Sheet23', 'Sheet24', 'Sheet25', 'Sheet26', 'Sheet27', 'Sheet28']

In [63]:
xl.parse("Sheet1", header=None)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2024-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Date,Break Fast,Lunch,Even. Snacks,Dinner,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,01.01.2024,14,40,4,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,02.01.2024,13,52,12,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,03.01.2024,26,87,26,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,04.01.2024,27,98,27,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,05.01.2024,20,135,11,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,06.01.2024,34,99,39,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,07.01.2024,32,70,28,208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,08.01.2024,160,450,137,330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,09.01.2024,195,422,226,350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,10.01.2024,194,556,198,470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,11.01.2024,174,408,260,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,12.01.2024,166,410,60,220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,13.01.2024,76,286,98,125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,14.01.2024,48,136,50,290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,15.01.2024,143,484,178,292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,16.01.2024,246,416,235,320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,17.01.2024,200,516,163,430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,18.01.2024,153,375,241,192,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,19.01.2024,119,226,40,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,20.01.2024,80,312,78,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,21.01.2024,39,165,65,290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,22.01.2024,102,348,120,327,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,23.01.2024,150,391,202,328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,24.01.2024,183,472,160,433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,25.01.2024,144,315,181,120,NaN,NaN,NaN,412845.0,NaN,332155.0,NaN,NaN
28,NaN,26.01.2024,60,315,41,130,NaN,NaN,NaN,16190.0,NaN,22715.0,NaN,NaN
29,NaN,27.01.2024,63,173,64,105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,28.01.2024,44,92,57,272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,29.01.2024,152,368,130,300,NaN,NaN,NaN,429035.0,NaN,354870.0,NaN,74165.0
32,NaN,30.01.2024,225,380,233,261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,31.01.2024,196,435,165,420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,Total,3378,8620,3449,6625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
sheet = xl.parse("Sheet6", header=None)

for i in range(len(sheet)):
    row = sheet.iloc[i]
    print(i, list(row))

0 [np.float64(nan), nan, 'June Closed', nan, nan, nan, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
1 [np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
2 [np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
3 [np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
4 [np.float64(nan), datetime.datetime(2024, 7, 1, 0, 0), nan, nan, nan, nan, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
5 [np.float64(nan), 'Date', 'Break Fast', 'Lunch', 'Even. Snacks', 'Dinner', np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
6 [np.float64(nan), '01.07.2024', 125, 311, 25, 172, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
7 [np.float64(nan), '02.07.2024', 153, 273, 44, 182, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
8 [np.float64(nan), '03.07.2024', 158, 364, 62, 277, np.float64(nan), nan, '04.07.2024', 'R&D Block', 'Rate', 'Total', np.float64(nan), np.float64(1625.0), nan]
9 [np.float64(nan), '04.07.2024', 169, 297, 85, 182, np.float64(nan), nan, 70, 'Tea/Coffee', 10, 700, np.float64(nan), np.float64(nan), nan]
10 [np.float64(nan), '05.07.2024', 169, 282, 55, 233, np.float64(nan), nan, 70, 'Samosa', 10, 700, np.float64(nan), np.float64(nan), nan]
11 [np.float64(nan), '06.07.2024', 120, 323, 53, 127, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
12 [np.float64(nan), '07.07.2024', 105, 166, 36, 241, np.float64(nan), nan, nan, nan, 'Total', 1400, np.float64(nan), np.float64(nan), nan]
13 [np.float64(nan), '08.07.2024', 158, 412, 52, 226, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
14 [np.float64(nan), '09.07.2024', 195, 333, 44, 297, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
15 [np.float64(nan), '10.07.2024', 211, 448, 94, 378, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
16 [np.float64(nan), '11.07.2024', 248, 262, 129, 260, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
17 [np.float64(nan), '12.07.2024', 253, 386, 57, 362, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
18 [np.float64(nan), '13.07.2024', 239, 414, 80, 254, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
19 [np.float64(nan), '14.07.2024', 130, 246, 76, 428, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
20 [np.float64(nan), '15.07.2024', 278, 541, 105, 322, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
21 [np.float64(nan), '16.07.2024', 283, 417, 114, 329, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
22 [np.float64(nan), '17.07.2024', 282, 465, 105, 439, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
23 [np.float64(nan), '18.07.2024', 292, 427, 161, 282, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
24 [np.float64(nan), '19.07.2024', 264, 422, 110, 367, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
25 [np.float64(nan), '20.07.2024', 222, 492, 90, 205, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
26 [np.float64(nan), '21.07.2024', 150, 304, 80, 394, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
27 [np.float64(nan), '22.07.2024', 280, 490, 125, 284, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
28 [np.float64(nan), '23.07.2024', 293, 368, 114, 319, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
29 [np.float64(nan), '24.07.2024', 240, 598, 140, 450, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
30 [np.float64(nan), '25.07.2024', 242, 418, 166, 266, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
31 [np.float64(nan), '26.07.2024', 228, 436, 100, 310, np.float64(nan), nan, 'Pax', 'Rate', nan, nan, np.float64(nan), np.float64(nan), nan]
32 [np.float64(nan), '27.07.2024', 193, 486, 75, 227, np.float64(nan), '27.07.2024', 17, 60, 1020, nan, np.float64(nan), np.float64(nan), nan]
33 [np.float64(nan), '28.07.2024', 140, 233, 73, 373, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
34 [np.float64(nan), '29.07.2024', 214, 491, 119, 259, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
35 [np.float64(nan), '30.07.2024', 258, 381, 75, 291, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), '`']
36 [np.float64(nan), '31.07.2024', 220, 471, 100, 420, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]
37 [np.float64(nan), 'Total', 5738, 10430, 2473, 8110, np.float64(nan), nan, nan, nan, nan, nan, np.float64(nan), np.float64(nan), nan]

In [71]:
header_row = None

for i in range(len(sheet)):
    row = sheet.iloc[i]
    if "Date" in list(row):
        header_row = i
        break

print(header_row)

5

In [72]:
header = sheet.iloc[header_row]

date_col = None
for i in range(len(header)):
    if header[i] == "Date":
        date_col = i
        break

print(date_col)

1

In [73]:
data = sheet.iloc[header_row + 1:, date_col:date_col + 5]
data.columns = ["Date", "Breakfast", "Lunch", "Evening_Snacks", "Dinner"]
data

          Date Breakfast  Lunch Evening_Snacks Dinner
6   01.07.2024       125    311             25    172
7   02.07.2024       153    273             44    182
8   03.07.2024       158    364             62    277
9   04.07.2024       169    297             85    182
10  05.07.2024       169    282             55    233
11  06.07.2024       120    323             53    127
12  07.07.2024       105    166             36    241
13  08.07.2024       158    412             52    226
14  09.07.2024       195    333             44    297
15  10.07.2024       211    448             94    378
16  11.07.2024       248    262            129    260
17  12.07.2024       253    386             57    362
18  13.07.2024       239    414             80    254
19  14.07.2024       130    246             76    428
20  15.07.2024       278    541            105    322
21  16.07.2024       283    417            114    329
22  17.07.2024       282    465            105    439
23  18.07.2024       292    427            161    282
24  19.07.2024       264    422            110    367
25  20.07.2024       222    492             90    205
26  21.07.2024       150    304             80    394
27  22.07.2024       280    490            125    284
28  23.07.2024       293    368            114    319
29  24.07.2024       240    598            140    450
30  25.07.2024       242    418            166    266
31  26.07.2024       228    436            100    310
32  27.07.2024       193    486             75    227
33  28.07.2024       140    233             73    373
34  29.07.2024       214    491            119    259
35  30.07.2024       258    381             75    291
36  31.07.2024       220    471            100    420
37       Total      5738  10430           2473   8110

In [74]:
data["Date"] = pd.to_datetime(data["Date"], format="%d.%m.%Y", errors="coerce")
data = data.dropna(subset=["Date"])
data

         Date Breakfast Lunch Evening_Snacks Dinner
6  2024-07-01       125   311             25    172
7  2024-07-02       153   273             44    182
8  2024-07-03       158   364             62    277
9  2024-07-04       169   297             85    182
10 2024-07-05       169   282             55    233
11 2024-07-06       120   323             53    127
12 2024-07-07       105   166             36    241
13 2024-07-08       158   412             52    226
14 2024-07-09       195   333             44    297
15 2024-07-10       211   448             94    378
16 2024-07-11       248   262            129    260
17 2024-07-12       253   386             57    362
18 2024-07-13       239   414             80    254
19 2024-07-14       130   246             76    428
20 2024-07-15       278   541            105    322
21 2024-07-16       283   417            114    329
22 2024-07-17       282   465            105    439
23 2024-07-18       292   427            161    282
24 2024-07-19       264   422            110    367
25 2024-07-20       222   492             90    205
26 2024-07-21       150   304             80    394
27 2024-07-22       280   490            125    284
28 2024-07-23       293   368            114    319
29 2024-07-24       240   598            140    450
30 2024-07-25       242   418            166    266
31 2024-07-26       228   436            100    310
32 2024-07-27       193   486             75    227
33 2024-07-28       140   233             73    373
34 2024-07-29       214   491            119    259
35 2024-07-30       258   381             75    291
36 2024-07-31       220   471            100    420

In [75]:
cleaned_sheets = []

for sheet_name in xl.sheet_names:
    
    sheet = xl.parse(sheet_name, header=None)
    
    header_row = None
    for i in range(len(sheet)):
        row = sheet.iloc[i]
        if "Date" in list(row):
            header_row = i
            break

    header = sheet.iloc[header_row]
    date_col = None
    for i in range(len(header)):
        if header[i] == "Date":
            date_col = i
            break

    data = sheet.iloc[header_row + 1:, date_col:date_col + 5]
    data.columns = ["Date", "Breakfast", "Lunch", "Evening_Snacks", "Dinner"]
    data["Date"] = pd.to_datetime(data["Date"], format="%d.%m.%Y", errors="coerce")
    data = data.dropna(subset=["Date"])

    cleaned_sheets.append(data)

print(len(cleaned_sheets))

28

In [78]:
full_data = pd.concat(cleaned_sheets, ignore_index=True)
full_data = full_data.sort_values("Date").reset_index(drop=True)
full_data

          Date Breakfast Lunch Evening_Snacks Dinner
0   2024-01-01        14    40              4     20
1   2024-01-02        13    52             12     32
2   2024-01-03        26    87             26     86
3   2024-01-04        27    98             27     60
4   2024-01-05        20   135             11     61
..         ...       ...   ...            ...    ...
847 2026-05-27        54   120             23    106
848 2026-05-28        56    95             16     91
849 2026-05-29        55    99             15    100
850 2026-05-30        45   135             16     38
851 2026-05-31        42    60             18     94

[852 rows x 5 columns]

In [107]:
print(full_data["Date"].min(), full_data["Date"].max())
print(full_data["Date"].duplicated().sum())
print(full_data.isna().sum())

2024-01-01 00:00:00 2026-05-31 00:00:00
0
Date              0
Breakfast         0
Lunch             0
Evening_Snacks    0
Dinner            0
DayOfWeek         0
dtype: int64

In [109]:
full_data.dtypes

Date              datetime64[us]
Breakfast                float64
Lunch                    float64
Evening_Snacks           float64
Dinner                   float64
DayOfWeek                    str
dtype: object

In [110]:
len(full_data)

836

In [111]:
train_data = full_data[full_data["Date"] < "2026-01-01"].reset_index(drop=True)
future_data = full_data[full_data["Date"] >= "2026-01-01"].reset_index(drop=True)

print(len(train_data), len(future_data))

685 151

In [112]:
train_data.to_csv("../data/processed/mess_data_2024_2025_clean.csv", index=False)
future_data.to_csv("../data/processed/mess_data_2026_holdout.csv", index=False)