In [12]:
import pandas as pd
import numpy as np

df_2425 = pd.read_csv("/home/grenzz/funnnn/ml/Mess-Meal-Forecasting/data/processed/2024-2025.csv", parse_dates=["Date"])
df_2026 = pd.read_csv("/home/grenzz/funnnn/ml/Mess-Meal-Forecasting/data/processed/2026.csv", parse_dates=["Date"])

In [13]:
assert set(df_2425.columns) == set(df_2026.columns), "Column mismatch!"

In [14]:
df_master = pd.concat([df_2425, df_2026], ignore_index=True).sort_values("Date").reset_index(drop=True)
df_master.head()

        Date  Breakfast  Lunch  Evening_Snacks  Dinner  DayOfWeek
0 2024-01-01       14.0   40.0             4.0    20.0     Monday
1 2024-01-02       13.0   52.0            12.0    32.0    Tuesday
2 2024-01-03       26.0   87.0            26.0    86.0  Wednesday
3 2024-01-04       27.0   98.0            27.0    60.0   Thursday
4 2024-01-05       20.0  135.0            11.0    61.0     Friday

In [15]:
df_master.shape

(836, 6)

In [16]:
df_calendar = pd.read_excel("/home/grenzz/funnnn/ml/Mess-Meal-Forecasting/data/processed/academic_calendar_2426.xlsx")
df_calendar.columns = ["Date", "Category", "Notes"]
df_calendar["Date"] = pd.to_datetime(df_calendar["Date"])
df_calendar["Category"] = df_calendar["Category"].replace({
    "winter vacation": "winter_vacation",
    "holdiay": "holiday"
})
df_calendar.head()

        Date         Category Notes
0 2024-01-01  winter_vacation   NaN
1 2024-01-02  winter_vacation   NaN
2 2024-01-03  winter_vacation   NaN
3 2024-01-04  winter_vacation   NaN
4 2024-01-05  winter_vacation   NaN

In [17]:
print(len(df_master))
print(len(df_calendar))

836
882

In [18]:
df_master = pd.merge(df_master, df_calendar, on="Date", how="left")
print(len(df_master))

836

In [19]:
df_master.columns.tolist()

['Date',
 'Breakfast',
 'Lunch',
 'Evening_Snacks',
 'Dinner',
 'DayOfWeek',
 'Category',
 'Notes']

In [20]:
df_master = df_master.set_index("Date").asfreq("D").reset_index()
print(len(df_master))

882

In [21]:
df_master[df_master["Breakfast"].isna()]

,Date,Breakfast,Lunch,Evening_Snacks,Dinner,DayOfWeek,Category,Notes
152,2024-06-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,2024-06-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,2024-06-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,2024-06-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,2024-06-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,2024-06-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,2024-06-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,2024-06-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,2024-06-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,2024-06-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,2024-06-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,2024-06-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,2024-06-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,2024-06-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,2024-06-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,2024-06-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,2024-06-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,2024-06-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,2024-06-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,2024-06-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,2024-06-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,2024-06-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,2024-06-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,2024-06-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,2024-06-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,2024-06-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,2024-06-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,2024-06-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,2024-06-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,2024-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342,2024-12-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,2024-12-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,2024-12-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,2024-12-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
346,2024-12-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,2024-12-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,2024-12-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,2024-12-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,2024-12-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,2024-12-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,2024-12-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,2024-12-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,2024-12-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355,2024-12-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356,2024-12-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
357,2024-12-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df_master["DayOfWeek"] = df_master["Date"].dt.day_name()

In [23]:
df_master.loc[df_master["Date"].between("2024-06-01", "2024-06-30"), "Category"] = "mess_closed"
df_master.loc[df_master["Date"].between("2024-12-08", "2024-12-23"), "Category"] = "mess_closed"

In [24]:
df_master["Category"].isna().sum()

np.int64(0)

In [25]:
df_master[df_master["Breakfast"].isna()]

,Date,Breakfast,Lunch,Evening_Snacks,Dinner,DayOfWeek,Category,Notes
152,2024-06-01,NaN,NaN,NaN,NaN,Saturday,mess_closed,NaN
153,2024-06-02,NaN,NaN,NaN,NaN,Sunday,mess_closed,NaN
154,2024-06-03,NaN,NaN,NaN,NaN,Monday,mess_closed,NaN
155,2024-06-04,NaN,NaN,NaN,NaN,Tuesday,mess_closed,NaN
156,2024-06-05,NaN,NaN,NaN,NaN,Wednesday,mess_closed,NaN
157,2024-06-06,NaN,NaN,NaN,NaN,Thursday,mess_closed,NaN
158,2024-06-07,NaN,NaN,NaN,NaN,Friday,mess_closed,NaN
159,2024-06-08,NaN,NaN,NaN,NaN,Saturday,mess_closed,NaN
160,2024-06-09,NaN,NaN,NaN,NaN,Sunday,mess_closed,NaN
161,2024-06-10,NaN,NaN,NaN,NaN,Monday,mess_closed,NaN
162,2024-06-11,NaN,NaN,NaN,NaN,Tuesday,mess_closed,NaN
163,2024-06-12,NaN,NaN,NaN,NaN,Wednesday,mess_closed,NaN
164,2024-06-13,NaN,NaN,NaN,NaN,Thursday,mess_closed,NaN
165,2024-06-14,NaN,NaN,NaN,NaN,Friday,mess_closed,NaN
166,2024-06-15,NaN,NaN,NaN,NaN,Saturday,mess_closed,NaN
167,2024-06-16,NaN,NaN,NaN,NaN,Sunday,mess_closed,NaN
168,2024-06-17,NaN,NaN,NaN,NaN,Monday,mess_closed,NaN
169,2024-06-18,NaN,NaN,NaN,NaN,Tuesday,mess_closed,NaN
170,2024-06-19,NaN,NaN,NaN,NaN,Wednesday,mess_closed,NaN
171,2024-06-20,NaN,NaN,NaN,NaN,Thursday,mess_closed,NaN
172,2024-06-21,NaN,NaN,NaN,NaN,Friday,mess_closed,NaN
173,2024-06-22,NaN,NaN,NaN,NaN,Saturday,mess_closed,NaN
174,2024-06-23,NaN,NaN,NaN,NaN,Sunday,mess_closed,NaN
175,2024-06-24,NaN,NaN,NaN,NaN,Monday,mess_closed,NaN
176,2024-06-25,NaN,NaN,NaN,NaN,Tuesday,mess_closed,NaN
177,2024-06-26,NaN,NaN,NaN,NaN,Wednesday,mess_closed,NaN
178,2024-06-27,NaN,NaN,NaN,NaN,Thursday,mess_closed,NaN
179,2024-06-28,NaN,NaN,NaN,NaN,Friday,mess_closed,NaN
180,2024-06-29,NaN,NaN,NaN,NaN,Saturday,mess_closed,NaN
181,2024-06-30,NaN,NaN,NaN,NaN,Sunday,mess_closed,NaN
342,2024-12-08,NaN,NaN,NaN,NaN,Sunday,mess_closed,NaN
343,2024-12-09,NaN,NaN,NaN,NaN,Monday,mess_closed,NaN
344,2024-12-10,NaN,NaN,NaN,NaN,Tuesday,mess_closed,NaN
345,2024-12-11,NaN,NaN,NaN,NaN,Wednesday,mess_closed,NaN
346,2024-12-12,NaN,NaN,NaN,NaN,Thursday,mess_closed,NaN
347,2024-12-13,NaN,NaN,NaN,NaN,Friday,mess_closed,NaN
348,2024-12-14,NaN,NaN,NaN,NaN,Saturday,mess_closed,NaN
349,2024-12-15,NaN,NaN,NaN,NaN,Sunday,mess_closed,NaN
350,2024-12-16,NaN,NaN,NaN,NaN,Monday,mess_closed,NaN
351,2024-12-17,NaN,NaN,NaN,NaN,Tuesday,mess_closed,NaN
352,2024-12-18,NaN,NaN,NaN,NaN,Wednesday,mess_closed,NaN
353,2024-12-19,NaN,NaN,NaN,NaN,Thursday,mess_closed,NaN
354,2024-12-20,NaN,NaN,NaN,NaN,Friday,mess_closed,NaN
355,2024-12-21,NaN,NaN,NaN,NaN,Saturday,mess_closed,NaN
356,2024-12-22,NaN,NaN,NaN,NaN,Sunday,mess_closed,NaN
357,2024-12-23,NaN,NaN,NaN,NaN,Monday,mess_closed,NaN

In [26]:
df_master = df_master.set_index('Date').asfreq('D').reset_index()
df_master['DayOfWeek'] = df_master['Date'].dt.day_name()
df_master.loc[df_master['Date'].between('2024-06-01', '2024-06-30'), 'Category'] = 'mess_closed'
df_master.loc[df_master['Date'].between('2024-12-08', '2024-12-23'), 'Category'] = 'mess_closed'

In [27]:
df_master[df_master["Breakfast"].isna()]

,Date,Breakfast,Lunch,Evening_Snacks,Dinner,DayOfWeek,Category,Notes
152,2024-06-01,NaN,NaN,NaN,NaN,Saturday,mess_closed,NaN
153,2024-06-02,NaN,NaN,NaN,NaN,Sunday,mess_closed,NaN
154,2024-06-03,NaN,NaN,NaN,NaN,Monday,mess_closed,NaN
155,2024-06-04,NaN,NaN,NaN,NaN,Tuesday,mess_closed,NaN
156,2024-06-05,NaN,NaN,NaN,NaN,Wednesday,mess_closed,NaN
157,2024-06-06,NaN,NaN,NaN,NaN,Thursday,mess_closed,NaN
158,2024-06-07,NaN,NaN,NaN,NaN,Friday,mess_closed,NaN
159,2024-06-08,NaN,NaN,NaN,NaN,Saturday,mess_closed,NaN
160,2024-06-09,NaN,NaN,NaN,NaN,Sunday,mess_closed,NaN
161,2024-06-10,NaN,NaN,NaN,NaN,Monday,mess_closed,NaN
162,2024-06-11,NaN,NaN,NaN,NaN,Tuesday,mess_closed,NaN
163,2024-06-12,NaN,NaN,NaN,NaN,Wednesday,mess_closed,NaN
164,2024-06-13,NaN,NaN,NaN,NaN,Thursday,mess_closed,NaN
165,2024-06-14,NaN,NaN,NaN,NaN,Friday,mess_closed,NaN
166,2024-06-15,NaN,NaN,NaN,NaN,Saturday,mess_closed,NaN
167,2024-06-16,NaN,NaN,NaN,NaN,Sunday,mess_closed,NaN
168,2024-06-17,NaN,NaN,NaN,NaN,Monday,mess_closed,NaN
169,2024-06-18,NaN,NaN,NaN,NaN,Tuesday,mess_closed,NaN
170,2024-06-19,NaN,NaN,NaN,NaN,Wednesday,mess_closed,NaN
171,2024-06-20,NaN,NaN,NaN,NaN,Thursday,mess_closed,NaN
172,2024-06-21,NaN,NaN,NaN,NaN,Friday,mess_closed,NaN
173,2024-06-22,NaN,NaN,NaN,NaN,Saturday,mess_closed,NaN
174,2024-06-23,NaN,NaN,NaN,NaN,Sunday,mess_closed,NaN
175,2024-06-24,NaN,NaN,NaN,NaN,Monday,mess_closed,NaN
176,2024-06-25,NaN,NaN,NaN,NaN,Tuesday,mess_closed,NaN
177,2024-06-26,NaN,NaN,NaN,NaN,Wednesday,mess_closed,NaN
178,2024-06-27,NaN,NaN,NaN,NaN,Thursday,mess_closed,NaN
179,2024-06-28,NaN,NaN,NaN,NaN,Friday,mess_closed,NaN
180,2024-06-29,NaN,NaN,NaN,NaN,Saturday,mess_closed,NaN
181,2024-06-30,NaN,NaN,NaN,NaN,Sunday,mess_closed,NaN
342,2024-12-08,NaN,NaN,NaN,NaN,Sunday,mess_closed,NaN
343,2024-12-09,NaN,NaN,NaN,NaN,Monday,mess_closed,NaN
344,2024-12-10,NaN,NaN,NaN,NaN,Tuesday,mess_closed,NaN
345,2024-12-11,NaN,NaN,NaN,NaN,Wednesday,mess_closed,NaN
346,2024-12-12,NaN,NaN,NaN,NaN,Thursday,mess_closed,NaN
347,2024-12-13,NaN,NaN,NaN,NaN,Friday,mess_closed,NaN
348,2024-12-14,NaN,NaN,NaN,NaN,Saturday,mess_closed,NaN
349,2024-12-15,NaN,NaN,NaN,NaN,Sunday,mess_closed,NaN
350,2024-12-16,NaN,NaN,NaN,NaN,Monday,mess_closed,NaN
351,2024-12-17,NaN,NaN,NaN,NaN,Tuesday,mess_closed,NaN
352,2024-12-18,NaN,NaN,NaN,NaN,Wednesday,mess_closed,NaN
353,2024-12-19,NaN,NaN,NaN,NaN,Thursday,mess_closed,NaN
354,2024-12-20,NaN,NaN,NaN,NaN,Friday,mess_closed,NaN
355,2024-12-21,NaN,NaN,NaN,NaN,Saturday,mess_closed,NaN
356,2024-12-22,NaN,NaN,NaN,NaN,Sunday,mess_closed,NaN
357,2024-12-23,NaN,NaN,NaN,NaN,Monday,mess_closed,NaN

In [28]:
df_master['DayOfMonth'] = df_master['Date'].dt.day
df_master['DayOfWeek_Num'] = df_master['Date'].dt.dayofweek
df_master['DayOfYear'] = df_master['Date'].dt.dayofyear
df_master['WeekOfYear'] = df_master['Date'].dt.isocalendar().week
df_master['Month'] = df_master['Date'].dt.month
df_master['Is_Start_Of_Month'] = (df_master['DayOfMonth'] <= 7).astype(int)
df_master['Is_End_Of_Month'] = (df_master['DayOfMonth'] >= 24).astype(int)
df_master['Is_Weekend'] = (df_master['DayOfWeek_Num'] >= 5).astype(int)

In [29]:
df_master['Is_Holiday'] = (df_master['Category'] == 'holiday').astype(int)
df_master['Is_Vacation'] = df_master['Category'].fillna('').str.contains('vacation', case=False).astype(int)
df_master['Is_Exam_Period'] = df_master['Category'].isin(['mid_sem_exams', 'end_sem_exams']).astype(int)

In [30]:
fest_keywords = 'odyssey|astra|esya|e summit|riise'
df_master['Is_Fest'] = df_master['Notes'].fillna('').str.contains(fest_keywords, case=False).astype(int)

In [31]:
df_master['Next_Holiday_Date'] = np.where(df_master['Is_Holiday'] == 1, df_master['Date'], pd.NaT)
df_master['Next_Holiday_Date'] = pd.to_datetime(df_master['Next_Holiday_Date']).bfill()
df_master['Days_Until_Holiday'] = (df_master['Next_Holiday_Date'] - df_master['Date']).dt.days.fillna(99)
df_master.drop(columns=['Next_Holiday_Date'], inplace=True)

In [32]:
df_master['DayOfWeek_Sin'] = np.sin(2 * np.pi * df_master['DayOfWeek_Num'] / 7)
df_master['DayOfWeek_Cos'] = np.cos(2 * np.pi * df_master['DayOfWeek_Num'] / 7)
df_master['Month_Sin'] = np.sin(2 * np.pi * df_master['Month'] / 12)
df_master['Month_Cos'] = np.cos(2 * np.pi * df_master['Month'] / 12)

In [33]:
df_master['Is_Broke_Weekend'] = df_master['Is_End_Of_Month'] * df_master['Is_Weekend']
df_master['Is_Rich_Weekend'] = df_master['Is_Start_Of_Month'] * df_master['Is_Weekend']

In [34]:
base_features = [
    'Date', 'DayOfWeek', 'DayOfMonth', 'Month', 'Is_Start_Of_Month',
    'Is_End_Of_Month', 'Is_Weekend', 'Is_Holiday', 'Is_Vacation',
    'Is_Exam_Period', 'Is_Fest', 'Days_Until_Holiday',
    'DayOfWeek_Sin', 'DayOfWeek_Cos', 'Month_Sin', 'Month_Cos',
    'Is_Broke_Weekend', 'Is_Rich_Weekend', 'WeekOfYear', 'DayOfYear'
]

In [32]:
meals = ['Breakfast', 'Lunch', 'Evening_Snacks', 'Dinner']

for meal in meals:
    meal_df = df_master[base_features + [meal]].copy()
    meal_df.rename(columns={meal: 'Target_Headcount'}, inplace=True)

    lags = [1, 2, 3, 7, 14, 21]
    for lag in lags:
        meal_df[f'Target_{lag}_Days_Ago'] = meal_df['Target_Headcount'].shift(lag)

    windows = [3, 7, 14, 28]
    for w in windows:
        meal_df[f'Target_{w}_Day_Avg'] = meal_df['Target_Headcount'].shift(1).rolling(window=w).mean()
        meal_df[f'Target_{w}_Day_Std'] = meal_df['Target_Headcount'].shift(1).rolling(window=w).std()
        meal_df[f'Target_{w}_Day_Max'] = meal_df['Target_Headcount'].shift(1).rolling(window=w).max()
        meal_df[f'Target_{w}_Day_Min'] = meal_df['Target_Headcount'].shift(1).rolling(window=w).min()

    meal_df['Target_EWMA_7'] = meal_df['Target_Headcount'].shift(1).ewm(span=7, adjust=False).mean()
    meal_df['Target_EWMA_14'] = meal_df['Target_Headcount'].shift(1).ewm(span=14, adjust=False).mean()
    meal_df['Trend_7_vs_28'] = meal_df['Target_7_Day_Avg'] / (meal_df['Target_28_Day_Avg'] + 1)

    output_filename = f"{meal}_feature_2024_2025.csv"
    meal_df.to_csv(output_filename, index=False)
    print(f" -> Saved {output_filename} (Rows: {len(meal_df)}, Columns: {len(meal_df.columns)})")

 -> Saved Breakfast_feature_2024_2025.csv (Rows: 731, Columns: 46)
 -> Saved Lunch_feature_2024_2025.csv (Rows: 731, Columns: 46)
 -> Saved Evening_Snacks_feature_2024_2025.csv (Rows: 731, Columns: 46)
 -> Saved Dinner_feature_2024_2025.csv (Rows: 731, Columns: 46)

In [36]:
meals = ['Breakfast', 'Lunch', 'Evening_Snacks', 'Dinner']
meal_frames_2026 = {}

for meal in meals:
    meal_df = df_master[base_features + [meal]].copy()
    meal_df.rename(columns={meal: 'Target_Headcount'}, inplace=True)

    lags = [1, 2, 3, 7, 14, 21]
    for lag in lags:
        meal_df[f'Target_{lag}_Days_Ago'] = meal_df['Target_Headcount'].shift(lag)

    windows = [3, 7, 14, 28]
    for w in windows:
        meal_df[f'Target_{w}_Day_Avg'] = meal_df['Target_Headcount'].shift(1).rolling(window=w).mean()
        meal_df[f'Target_{w}_Day_Std'] = meal_df['Target_Headcount'].shift(1).rolling(window=w).std()
        meal_df[f'Target_{w}_Day_Max'] = meal_df['Target_Headcount'].shift(1).rolling(window=w).max()
        meal_df[f'Target_{w}_Day_Min'] = meal_df['Target_Headcount'].shift(1).rolling(window=w).min()

    meal_df['Target_EWMA_7'] = meal_df['Target_Headcount'].shift(1).ewm(span=7, adjust=False).mean()
    meal_df['Target_EWMA_14'] = meal_df['Target_Headcount'].shift(1).ewm(span=14, adjust=False).mean()
    meal_df['Trend_7_vs_28'] = meal_df['Target_7_Day_Avg'] / (meal_df['Target_28_Day_Avg'] + 1)

    meal_df_2026 = meal_df[(meal_df["Date"] >= "2026-01-01")].copy()

    meal_frames_2026[meal] = meal_df_2026

    output_filename = f"{meal}_feature_2026.csv"
    meal_df_2026.to_csv(output_filename, index=False)
    print(f" -> Saved {output_filename} (Rows: {len(meal_df_2026)}, Columns: {len(meal_df_2026.columns)})")
    print(f"    NaNs remaining: {meal_df_2026.isna().sum().sum()}")

 -> Saved Breakfast_feature_2026.csv (Rows: 151, Columns: 46)
    NaNs remaining: 0
 -> Saved Lunch_feature_2026.csv (Rows: 151, Columns: 46)
    NaNs remaining: 0
 -> Saved Evening_Snacks_feature_2026.csv (Rows: 151, Columns: 46)
    NaNs remaining: 0
 -> Saved Dinner_feature_2026.csv (Rows: 151, Columns: 46)
    NaNs remaining: 0

In [38]:
existing = pd.read_csv("/home/grenzz/funnnn/ml/Mess-Meal-Forecasting/data/processed/Dinner_feature_2024_2025.csv")
new = meal_frames_2026["Dinner"]
print("\nColumn parity check (Dinner):")
print("Same columns, same order:", list(existing.columns) == list(new.columns))
print("Missing from new:", set(existing.columns) - set(new.columns))
print("Extra in new:", set(new.columns) - set(existing.columns))

Column parity check (Dinner):
Same columns, same order: True
Missing from new: set()
Extra in new: set()